using Microsoft.Maui.ApplicationModel;

namespace PlainWallet.Views;

public partial class ExtendsClassInfoPage : ContentPage
{
    public ExtendsClassInfoPage()
    {
        InitializeComponent();
        InfoWebView.Source = new HtmlWebViewSource
        {
            Html = """
                <!doctype html>
                <html lang="en">
                <head>
                    <meta charset="UTF-8">
                    <meta name="viewport" content="width=device-width, initial-scale=1.0">
                    <title>How Syncing Works</title>
                <style>
                h1 {
                            color: #1a73e8;
                    }                
                .field-title {
                            font-weight: bold;
                            font-size: 16px;
                            color: #202124;
                            display: flex;
                            align-items: center;
                            gap: 6px;
                        }
                </style>   
                </head>
                <body>

                <div class="container">
                    <h1>🔄 How Syncing Works</h1>
                    <p>This app allows you to sync your data across multiple devices for free. Instead of saving your data on an unsafe public server, you save it inside your own private storage locker that <strong>only you</strong> control.</p> 

                    <p>To make this work, the app uses three settings:</p>

                    <div class="field-section">
                        <div class="field-title">🔑 1. Api-key</div>
                        <ul>
                            <li><strong>What it is:</strong> Your account username for the storage service.</li>
                            <li><strong>How to get it:</strong> Go to <a href="https://extendsclass.com">extendsclass.com</a>, create a free account under <strong>My Account</strong>, and copy the API key from your dashboard.</li>
                            <li><strong>Why it's needed:</strong> This tells the server which free account quota to use so you never have to pay for syncing.</li>
                        </ul>
                    </div>

                    <div class="field-section">
                        <div class="field-title">🔒 2. Security-key</div>
                        <ul>
                            <li><strong>What it is:</strong> Your master password and encryption key.</li>
                            <li><strong>How to get it:</strong> You make this up yourself! Create a strong, private password.</li>
                            <li><strong>Why it's needed:</strong> The app uses this key to <strong>scramble and encrypt your data before it ever leaves your device</strong>. Even the storage website cannot read your information. <em>Keep this safe—without it, your synced devices cannot unlock your data.</em></li>
                        </ul>
                    </div>

                    <div class="field-section">
                        <div class="field-title">📦 3. Bin id</div>
                        <ul>
                            <li><strong>What it is:</strong> The unique address of your digital storage box.</li>
                            <li><strong>How to get it:</strong> 
                                <ul>
                                    <li><strong>On your first device:</strong> Leave this blank. The app will automatically create a box for you and generate a Bin id.</li>
                                    <li><strong>On your other devices:</strong> Copy the exact Bin id generated by your first device to link them together.</li>
                                </ul>
                            </li>
                        </ul>
                    </div>

                    <h2>🚀 Quick Setup Summary</h2>
                    <ol class="step-list">
                        <li><strong>On Device 1:</strong> Paste your <span class="highlight">Api-key</span>, create a private <span class="highlight">Security-key</span>, and leave <span class="highlight">Bin id</span> blank. Tap "Apply"</li>
                        <li><strong>On Device 2+:</strong> Copy the <span class="highlight">Api-key</span>, <span class="highlight">Security-key</span>, and the newly generated <span class="highlight">Bin id</span> from your first device. Paste them in and tap "Apply"</li>
                    </ol>
                </div>

                </body>

                </html>
                """
        };
    }

    private async void OnInfoWebViewNavigating(object? sender, WebNavigatingEventArgs e)
    {
        if (!Uri.TryCreate(e.Url, UriKind.Absolute, out var uri) ||
            (uri.Scheme != Uri.UriSchemeHttp && uri.Scheme != Uri.UriSchemeHttps))
        {
            return;
        }

        e.Cancel = true;
        try
        {
            await Browser.Default.OpenAsync(uri, BrowserLaunchMode.SystemPreferred);
        }
        catch (Exception exception)
        {
            await DisplayAlertAsync("Browser Error", $"Could not open the link: {exception.Message}", "OK");
        }
    }

    private async void OnCloseClicked(object? sender, EventArgs e)
    {
        await Navigation.PopAsync();
    }
}